# Generated by Django 4.0.4 on 2022-06-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='job名称')),
                ('remote_ip', models.CharField(max_length=15, verbose_name='远程服务器IP')),
                ('remote_port', models.IntegerField(verbose_name='远程服务器端口')),
                ('remote_cmd', models.CharField(max_length=100, verbose_name='完整执行命令')),
                ('remote_name', models.CharField(max_length=15, verbose_name='远程服务器用户名')),
                ('remote_password', models.CharField(max_length=15, verbose_name='远程服务器密码')),
                ('timeout', models.IntegerField(default=300, verbose_name='脚本执行超时设置,单位秒')),
                ('cron_exp', models.CharField(max_length=30, verbose_name='标准cron表达式')),
                ('use_flag', models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=1, verbose_name='是否启用')),
                ('current_status', models.CharField(choices=[('Y', '执行中'), ('N', '就绪')], default='N', max_length=1, verbose_name='当前是否在执行')),
                ('comment', models.CharField(blank=True, max_length=30, verbose_name='注释')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '运维平台定时任务的配置',
                'verbose_name_plural': '运维平台定时任务的配置',
                'db_table': 'OMP_CRON_JOBS',
            },
        ),
        migrations.CreateModel(
            name='CronJobsHistory',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('job_id', models.IntegerField(verbose_name='job主键')),
                ('job_name', models.CharField(max_length=10, verbose_name='job名称')),
                ('job_detail', models.CharField(max_length=100, verbose_name='用户名@IP：命令')),
                ('result', models.CharField(choices=[('Y', '成功'), ('N', '失败')], max_length=1, verbose_name='本次运行结果')),
                ('start_time', models.DateTimeField(verbose_name='本次开始时间')),
                ('end_time', models.DateTimeField(verbose_name='本次结束时间')),
            ],
            options={
                'verbose_name': '存放定时任务执行历史记录',
                'verbose_name_plural': '存放定时任务执行历史记录',
                'db_table': 'OMP_CRON_JOBS_HIST',
            },
        ),
        migrations.CreateModel(
            name='FmAlarmEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='邮箱地址')),
                ('use_flag', models.CharField(choices=[('Y', '是'), ('N', '否')], default='Y', max_length=1, verbose_name='是否启用')),
                ('comment', models.CharField(blank=True, max_length=30, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'FM报警发送邮箱列表',
                'verbose_name_plural': 'FM报警发送邮箱列表',
                'db_table': 'OMP_FM_ALARM_EMAIL',
            },
        ),
        migrations.CreateModel(
            name='FmAlarmEmailConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='配置名称')),
                ('value', models.CharField(max_length=30, verbose_name='配置值')),
                ('comment', models.CharField(blank=True, max_length=30, verbose_name='参数项备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'FM报警通知间隔、报警数量边界等配置',
                'verbose_name_plural': 'FM报警通知间隔、报警数量边界等配置',
                'db_table': 'OMP_FM_ALARM_EMAIL_CONFIG',
            },
        ),
    ]
