# Generated by Django 4.0.4 on 2022-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolPlatformApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobs',
            name='remote_port',
            field=models.CharField(max_length=5, verbose_name='远程服务器端口'),
        ),
        migrations.AlterField(
            model_name='cronjobs',
            name='timeout',
            field=models.CharField(default=300, max_length=5, verbose_name='脚本执行超时设置,单位秒'),
        ),
    ]
