# Generated by Django 4.0.4 on 2022-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolPlatformApp', '0002_alter_cronjobs_remote_port_alter_cronjobs_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobshistory',
            name='end_time',
            field=models.DateTimeField(blank=True, verbose_name='本次结束时间'),
        ),
    ]
