# Generated by Django 4.0.4 on 2022-06-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolPlatformApp', '0004_alter_cronjobshistory_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobshistory',
            name='err_mess',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='报错信息'),
        ),
    ]
