# Generated by Django 4.0.4 on 2022-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolPlatformApp', '0005_cronjobshistory_err_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobs',
            name='comment',
            field=models.CharField(blank=True, max_length=50, verbose_name='注释'),
        ),
    ]
