# Generated by Django 4.0.4 on 2022-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolPlatformApp', '0006_alter_cronjobs_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobshistory',
            name='err_mess',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='报错信息'),
        ),
    ]
