# Generated by Django 4.0.4 on 2022-06-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolPlatformApp', '0007_alter_cronjobshistory_err_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobshistory',
            name='job_name',
            field=models.CharField(max_length=30, verbose_name='job名称'),
        ),
    ]
