# Generated by Django 4.0.4 on 2022-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolPlatformApp', '0008_alter_cronjobshistory_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronFunctionJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('fun_name', models.CharField(max_length=30, unique=True, verbose_name='内部业务函数名称')),
                ('fun_args', models.CharField(default='()', max_length=50, verbose_name='内部函数传参（元组格式）')),
                ('cron_exp', models.CharField(max_length=30, verbose_name='标准cron表达式')),
                ('use_flag', models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=1, verbose_name='是否启用')),
                ('purpose', models.CharField(blank=True, max_length=50, verbose_name='作用/用途')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '运维平台内部函数定时任务',
                'verbose_name_plural': '运维平台内部函数定时任务',
                'db_table': 'OMP_CRON_FUN_JOBS',
            },
        ),
    ]
