# Generated by Django 4.0.4 on 2022-06-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolPlatformApp', '0009_cronfunctionjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobshistory',
            name='job_detail',
            field=models.CharField(max_length=200, verbose_name='用户名@IP：命令'),
        ),
    ]
